### ISSUE TITLE
Alpine build error due changes to proj

### ISSUE THREAD

**Issue by BWibo** [tum-gis/3dcitydb-docker-postgis#10]
Build fails because due to changes to proj alpine package:
See here:
* [https://gitlab.alpinelinux.org/alpine/aports/issues/10612](https://gitlab.alpinelinux.org/alpine/aports/issues/10612)
* timescale/timescaledb-docker#75
* appropriate/docker-postgis#146

**Comment by jrzerr** [comment]
Stumbled across this issue due to my own problems with the alpine postgis build.  I had to compile proj 4.9.3 from scratch (the version recommended for postgis 2.5.2 I was using), then point postgis configure to the src directory using --with-projdir.

**Comment by BWibo** [comment]
Thx, for your feedback, I was considering doing that as well. Its good to know you can confirm this works. 

However, I might as well wait just for PostGIS 3.0 which is being released soon. According to [this](https://postgis.net/2019/10/20/postgis-3.0.0/) PostGIS 3 is going to support the proj 6+.

**Comment by BWibo** [comment]
Resolved by updating to postgresql-12 and postgis 3.0 in db171a801e5af5e3bda4eaa70af226d2ee361b05.
