### ISSUE TITLE
Build failing after latest Alpine/Postgres update

### ISSUE THREAD

**Issue by braderhart** [tum-gis/3dcitydb-docker-postgis#11]
Builds are failing after the latest Alpine/Postgre updates. Updated Dockerfile reference here:

https://gitlab.com/equalos/skaffold/blob/master/postgis/docker/postgis/Dockerfile

Please let me know if you find any issues.

**Comment by BWibo** [comment]
Seems to be working fine, thank you! Fixed in ac03d56537f62422905606a8f994076370b20178.
